apiVersion: ENC[AES256_GCM,data:X0I=,iv:tkXTNCYMF2RN/DtLyJV8Z5JWPCY9MGlc8IkkebkC+Ak=,tag:uYOOPoJiHdtpFAc5eN5FHg==,type:str]
kind: ENC[AES256_GCM,data:uNosPi+E,iv:nf8B0UE6EDX+OFnofehWPJPdAYVUtWSOAfdvoTZRuZ8=,tag:X9Fm2oN1fZusLDskLlBTkA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mN7qlCKuMA61OdMa,iv:09a0w/UsqTLsOX9JZT+0l5vAUzaundjS2OYyPUd+soU=,tag:kj00X3qmtHTJ67wcByhvvQ==,type:str]
    namespace: ENC[AES256_GCM,data:L4KEH3RZ,iv:Ko5VK5/Vt+5BdjnXLHqt5BtKEFzEqD4A8POgR17kUos=,tag:0kULiyKzrAjfHjSOAcg2Bg==,type:str]
type: ENC[AES256_GCM,data:n7dNaN4N,iv:ds/vET7rvpnxVybSNSRwLNDPZ5WfsLf1pC2OMy6eZEk=,tag:Dx8XOdiu6CbymcByKtaznw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:LEzzUQ==,iv:Ixp5IUnd+5V+ri/Wpel/72b6BsicDawnA1UXo2E66D8=,tag:qFeuR+eeKibR9R8LT0nB0Q==,type:str]
    password: ENC[AES256_GCM,data:By4+OT5jSwQhIw==,iv:NZnoJuMTdAnX876yqqL3yuBaZT/JfJgSLrscx2IUP24=,tag:nESCeM5Vfzcg2Hmwws5wjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10ac06ml9mv2vesnnrct77hsrjwj72l2v8ly8mjkjzsc6qtsgq50sy83u44
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbkxhR0xONTZiOWpJN1Q4
            Z3JmTmpSWFc3WHNUa0hsVDhUYkZPK2l2Um5jCm9WR0hPNVJhQWY1cGJqU0dVYVVT
            SkE3ZzQxUnE3V3BrdWtGeTFXSzlDdjgKLS0tIEVzbjJOVXM4b3hkTEpOUU9reG5p
            Y1g3eGhmMVpUS0tNUWtCTGNoZlVjdzQKVJ7x/nvaBl6P2wFzHzyAJuv7CcODRVMP
            sPBzMP1zbytBri8ey0zE6h+IYphboIlh5ejlc4f/FLbpyr5Pxz4lPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T08:16:48Z"
    mac: ENC[AES256_GCM,data:RYqNEjrrShc28HC80vIuR0H+pzLKN4XGWQZNJlNTaVOy1wJcfNWqwN2O8Kvfe7BLQghNWSZwEFWn0ViUu/99iFQntA50IZ19oapv+mId5LaTqEgG7HzAa1mfrvFINQwh+rF+prjj65iTL5h8GKlj5tlujnWaR+GEVVCzAa1x0hE=,iv:Oayii9+ES5va18IhWLCNkbE1zgXNtLUZY5gu7tSd9ns=,tag:w4+Z75CsaFLwwr7Ic0/MqA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
