apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-controller
  namespace: metallb-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metallb
  template:
    metadata:
      labels:
        app: metallb
    spec:
      containers:
        - name: controller
          image: metallb/controller:v0.13.11
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.17.0.10-172.17.0.20

