apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: fluxcd
spec:
  interval: 1m
  path: "./deploy/ingress-nginx"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-nginxapp-sot
    namespace: fluxcd

